import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * BrokerPerformanceSummary - Ranking of brokers by commission metrics
 * Shows: Deals, Earned, Approved, Pending, Approval rate
 */
export default function BrokerPerformanceSummary({ data, loading = false, }) {
    if (loading) {
        return (_jsx("div", { className: "flex items-center justify-center py-8", children: _jsx("div", { className: "w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" }) }));
    }
    if (data.length === 0) {
        return (_jsx("div", { className: "text-center py-8 text-slate-600", children: _jsx("p", { children: "No broker data available" }) }));
    }
    return (_jsxs("div", { className: "overflow-x-auto", children: [_jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-200", children: [_jsx("th", { className: "text-left px-4 py-3 font-semibold text-slate-900", children: "Broker" }), _jsx("th", { className: "text-center px-4 py-3 font-semibold text-slate-900", children: "Deals" }), _jsx("th", { className: "text-right px-4 py-3 font-semibold text-slate-900", children: "Total Earned" }), _jsx("th", { className: "text-right px-4 py-3 font-semibold text-slate-900", children: "Approved" }), _jsx("th", { className: "text-right px-4 py-3 font-semibold text-slate-900", children: "Pending" }), _jsx("th", { className: "text-center px-4 py-3 font-semibold text-slate-900", children: "Approval %" })] }) }), _jsx("tbody", { children: data.map((broker, index) => {
                            const approvalRate = parseFloat(broker.approvalRate);
                            const isTopPerformer = index === 0;
                            return (_jsxs("tr", { className: `border-b border-slate-200 transition ${isTopPerformer ? "bg-amber-50" : index % 2 === 0 ? "bg-slate-50" : "bg-white"} hover:bg-blue-50`, children: [_jsx("td", { className: "px-4 py-3", children: _jsxs("div", { className: "flex items-center gap-2", children: [isTopPerformer && _jsx("span", { className: "text-xl", children: "\uD83D\uDC51" }), _jsx("div", { children: _jsxs("p", { className: "font-semibold text-slate-900", children: ["#", index + 1, " ", broker.agentName] }) })] }) }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsx("span", { className: "inline-block px-3 py-1 bg-slate-100 text-slate-700 rounded font-semibold text-xs", children: broker.dealCount }) }), _jsxs("td", { className: "px-4 py-3 text-right font-semibold text-slate-900", children: ["AED ", (broker.totalEarned / 1000000).toFixed(1), "M"] }), _jsxs("td", { className: "px-4 py-3 text-right font-semibold text-emerald-700", children: ["AED ", (broker.approved / 1000000).toFixed(1), "M"] }), _jsxs("td", { className: "px-4 py-3 text-right font-semibold text-amber-700", children: ["AED ", (broker.pending / 1000000).toFixed(1), "M"] }), _jsx("td", { className: "px-4 py-3 text-center", children: _jsxs("div", { className: "flex items-center gap-2 justify-center", children: [_jsx("div", { className: "w-20 bg-slate-200 rounded-full h-2 overflow-hidden", children: _jsx("div", { className: `h-full rounded-full transition-all ${approvalRate > 80 ? "bg-emerald-500" : "bg-amber-500"}`, style: { width: `${approvalRate}%` } }) }), _jsxs("span", { className: `font-semibold text-xs whitespace-nowrap ${approvalRate > 80 ? "text-emerald-700" : "text-amber-700"}`, children: [broker.approvalRate, "%"] })] }) })] }, broker.agentId));
                        }) })] }), _jsxs("div", { className: "border-t border-slate-200 pt-4 mt-4 grid grid-cols-4 gap-3 text-center", children: [_jsxs("div", { className: "bg-slate-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-slate-600", children: "Total Brokers" }), _jsx("p", { className: "text-lg font-bold text-slate-900", children: data.length })] }), _jsxs("div", { className: "bg-slate-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-slate-600", children: "Total Deals" }), _jsx("p", { className: "text-lg font-bold text-slate-900", children: data.reduce((sum, b) => sum + b.dealCount, 0) })] }), _jsxs("div", { className: "bg-slate-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-slate-600", children: "Total Earned" }), _jsxs("p", { className: "text-lg font-bold text-slate-900", children: ["AED ", (data.reduce((sum, b) => sum + b.totalEarned, 0) / 1000000).toFixed(1), "M"] })] }), _jsxs("div", { className: "bg-amber-50 rounded p-3", children: [_jsx("p", { className: "text-xs text-slate-600", children: "Avg Approval %" }), _jsxs("p", { className: "text-lg font-bold text-amber-700", children: [(data.reduce((sum, b) => sum + parseFloat(b.approvalRate), 0) / data.length).toFixed(0), "%"] })] })] })] }));
}
