import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
const DEAL_STAGE_LABELS = {
    ENQUIRY: "Enquiry", QUALIFICATION: "Qualification", SITE_VISIT: "Site Visit",
    NEGOTIATION: "Negotiation", OFFER_SENT: "Offer Sent", ACCEPTED: "Accepted",
    PENDING: "Pending", COMPLETED: "Completed", LOST: "Lost",
};
function daysUntil(dateStr) {
    return Math.ceil((new Date(dateStr).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
}
export default function UnitCommercialPanel({ unit }) {
    const navigate = useNavigate();
    const activeDeal = unit.deals?.[0];
    const activeReservation = unit.reservations?.[0];
    const interests = unit.interests ?? [];
    const hasCommercialContext = activeDeal || activeReservation || interests.length > 0;
    if (!hasCommercialContext && unit.status === "NOT_RELEASED")
        return null;
    return (_jsxs("div", { className: "space-y-3", children: [activeDeal && (_jsxs("div", { className: "bg-white rounded-lg border border-violet-200 p-5", children: [_jsx("p", { className: "text-xs font-semibold text-violet-600 uppercase tracking-wide mb-3", children: "Active Deal" }), _jsxs("div", { className: "space-y-2 mb-3", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Deal #" }), _jsx("span", { className: "text-xs font-mono font-semibold text-slate-800", children: activeDeal.dealNumber })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Buyer" }), _jsxs("span", { className: "text-xs font-semibold text-slate-800", children: [activeDeal.lead.firstName, " ", activeDeal.lead.lastName] })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Stage" }), _jsx("span", { className: "text-xs font-semibold text-blue-700 bg-blue-50 px-2 py-0.5 rounded-full", children: DEAL_STAGE_LABELS[activeDeal.stage] || activeDeal.stage })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Sale Price" }), _jsxs("span", { className: "text-xs font-bold text-slate-900", children: ["AED ", activeDeal.salePrice.toLocaleString("en-AE")] })] })] }), _jsx("button", { onClick: () => navigate(`/deals/${activeDeal.id}`), className: "w-full px-3 py-2 bg-violet-600 hover:bg-violet-700 text-white text-xs font-semibold rounded-lg transition-colors", children: "Open Deal" })] })), activeReservation && (_jsxs("div", { className: "bg-white rounded-lg border border-amber-200 p-5", children: [_jsx("p", { className: "text-xs font-semibold text-amber-600 uppercase tracking-wide mb-3", children: "Reservation" }), _jsxs("div", { className: "space-y-2 mb-3", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Reserved by" }), _jsxs("span", { className: "text-xs font-semibold text-slate-800", children: [activeReservation.lead.firstName, " ", activeReservation.lead.lastName] })] }), activeReservation.lead.phone && (_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Phone" }), _jsx("span", { className: "text-xs text-slate-700", children: activeReservation.lead.phone })] })), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs text-slate-500", children: "Expires" }), _jsx("span", { className: `text-xs font-semibold ${daysUntil(activeReservation.expiresAt) <= 2 ? "text-red-600" : "text-slate-800"}`, children: daysUntil(activeReservation.expiresAt) > 0
                                            ? `${daysUntil(activeReservation.expiresAt)}d remaining`
                                            : "Expired" })] })] }), _jsx("button", { onClick: () => navigate(`/leads/${activeReservation.lead.id}`), className: "w-full px-3 py-2 border border-amber-300 bg-amber-50 hover:bg-amber-100 text-amber-800 text-xs font-semibold rounded-lg transition-colors", children: "View Lead Profile" })] })), interests.length > 0 && (_jsxs("div", { className: "bg-white rounded-lg border border-slate-200 p-5", children: [_jsx("div", { className: "flex items-center justify-between mb-3", children: _jsxs("p", { className: "text-xs font-semibold text-slate-600 uppercase tracking-wide", children: ["Interested Leads", _jsx("span", { className: "ml-2 bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded-full text-xs font-bold", children: interests.length })] }) }), _jsxs("div", { className: "space-y-2", children: [interests.slice(0, 4).map((interest) => (_jsxs("button", { onClick: () => navigate(`/leads/${interest.leadId}`), className: "w-full flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-slate-50 transition-colors text-left", children: [_jsxs("div", { className: "w-7 h-7 rounded-full bg-blue-100 text-blue-700 text-xs font-bold flex items-center justify-center flex-shrink-0", children: [interest.lead.firstName[0], interest.lead.lastName[0]] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("p", { className: "text-xs font-semibold text-slate-800 truncate", children: [interest.lead.firstName, " ", interest.lead.lastName, interest.isPrimary && (_jsx("span", { className: "ml-1.5 text-[10px] bg-emerald-100 text-emerald-700 px-1 py-0.5 rounded font-bold", children: "Primary" }))] }), _jsx("p", { className: "text-[10px] text-slate-400", children: interest.lead.stage?.replace(/_/g, " ") })] })] }, interest.leadId))), interests.length > 4 && (_jsxs("p", { className: "text-xs text-slate-400 text-center pt-1", children: ["+", interests.length - 4, " more"] }))] }), unit.status === "AVAILABLE" && (_jsx("div", { className: "mt-3 pt-3 border-t border-slate-100", children: _jsx("button", { onClick: () => navigate(`/deals?unitId=${unit.id}`), className: "w-full px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-lg transition-colors", children: "+ Create Deal" }) }))] })), !activeDeal && !activeReservation && interests.length === 0 && unit.status === "AVAILABLE" && (_jsxs("div", { className: "bg-white rounded-lg border border-dashed border-slate-300 p-5 text-center", children: [_jsx("p", { className: "text-xs text-slate-400 mb-2", children: "No active deal or leads yet" }), _jsx("button", { onClick: () => navigate(`/deals?unitId=${unit.id}`), className: "px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-lg transition-colors", children: "+ Create Deal" })] }))] }));
}
