import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function UnitFloorPlans({ images, onOpenFloorPlan }) {
    const floorPlans = images.filter((img) => img.type === "FLOOR_PLAN");
    const floorMaps = images.filter((img) => img.type === "FLOOR_MAP");
    if (floorPlans.length === 0 && floorMaps.length === 0)
        return null;
    const renderGrid = (items) => (_jsx("div", { className: "grid grid-cols-2 gap-3", children: items.map((plan) => (_jsxs("button", { onClick: () => onOpenFloorPlan(plan), className: "group relative rounded-lg overflow-hidden border-2 border-slate-200 hover:border-blue-400 transition-colors", children: [_jsx("img", { src: plan.url, alt: plan.caption || "Image", className: "w-full h-32 object-cover group-hover:brightness-110 transition-all" }), _jsx("div", { className: "absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center", children: _jsx("span", { className: "text-white text-2xl opacity-0 group-hover:opacity-100 transition-opacity", children: "\uD83D\uDC41\uFE0F" }) }), plan.caption && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 bg-black/60 text-white text-xs px-2 py-1 truncate", children: plan.caption }))] }, plan.id))) }));
    return (_jsxs("div", { className: "space-y-4", children: [floorPlans.length > 0 && (_jsxs("div", { className: "bg-white rounded-lg border border-slate-200 p-5", children: [_jsxs("p", { className: "text-xs font-semibold text-slate-500 uppercase tracking-wide mb-4", children: ["Floor Plans", _jsx("span", { className: "ml-2 bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded-full text-xs", children: floorPlans.length })] }), renderGrid(floorPlans)] })), floorMaps.length > 0 && (_jsxs("div", { className: "bg-white rounded-lg border border-slate-200 p-5", children: [_jsxs("p", { className: "text-xs font-semibold text-slate-500 uppercase tracking-wide mb-4", children: ["Floor Location Map", _jsx("span", { className: "ml-2 bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded-full text-xs", children: floorMaps.length })] }), renderGrid(floorMaps)] }))] }));
}
